version: '2'
services:
    db:
        image: postgres:13
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
        ports:
            - 5428:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=12345
            - PGDATA=/var/lib/postgresql/data/pgdata